config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :users

  resources :projects do
      resources :bugs
  end

  resources :bugs, only: [:index]

  match "/change_status" => "bugs#change_status", via: [:post]
  match "/bug_status" => "bugs#bug_status", via: [:post]
  root 'users#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bug.rb
class Bug < ApplicationRecord

  include Filter

  has_attached_file :screen_shot, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :screen_shot, :content_type => /^image\/(png|gif)/

  belongs_to :creator, class_name: "User"
  belongs_to :user
  belongs_to :project

  validates :bug_type, presence: true
  validates :status, presence: true

  scope :feature, -> { where(bug_type: StatusConstant::FEATURE) }
  scope :bug, -> { where(bug_type: StatusConstant::BUG) }

  enum bug_type: ["feature", "bug"]

  FEATURE_STATUS = ['new', 'started', 'completed']
  BUG_STATUS = ['new', 'started', 'resolved']

  def check_bug
    return self.bug_type == StatusConstant::BUG
  end

  def check_feature
    return self.bug_type == StatusConstant::FEATURE
  end
end

app/models/concerns/filter.rb
module Filter
  extend ActiveSupport::Concern

  included do
    validates :title, uniqueness: true, presence: true
  end

  def self.included(base)
    base.class_eval do
      scope :newest_first, -> { order("created_at DESC") }
    end
  end
  
end

app/models/field_values/role_constant.rb
class RoleConstant
  MANAGER = "manager"
  QA = "qa"
  DEVELOPER = "developer"
end

app/models/field_values/status_constant.rb
class StatusConstant
  FEATURE = "feature"
  BUG = "bug"
end

app/models/project.rb
class Project < ApplicationRecord

  include Filter

  has_and_belongs_to_many :users
  has_many :bugs
  
end

app/models/user.rb
class User < ApplicationRecord

  enum user_type: ["developer", "manager", "qa"]
  devise :database_authenticatable, :registerable, :recoverable, stretches: 12
  has_many :bugs
  has_many :created_bugs, class_name: 'Bug', :foreign_key => 'creator_id'

  scope :developers, -> { where(user_type: RoleConstant::DEVELOPER) }

  has_and_belongs_to_many :projects
  validates :name, presence: true
  validates :user_type, presence: true

  def has_role role
    return self.user_type == role
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bugs_controller.rb
class BugsController < ApplicationController

  before_action :authenticate_user!
  before_action :set_project, only: [:new, :edit, :create, :show]
  before_action :get_users, only: [:new, :create]

  def index
    if current_user.has_role RoleConstant::DEVELOPER
      @bugs = current_user.bugs.newest_first
    elsif current_user.has_role RoleConstant::QA
      @bugs = current_user.created_bugs.newest_first
    else
      @bugs = Bug.all
    end
  end

  def new
    @bug = Bug.new
  end

  def show
    @bugs = @project.bugs
  end

  def create
    @bug = Bug.new(bug_params)
    respond_to do |format|
      if @bug.save
        flash[:success]= "Project was successfully created."
        format.html { redirect_to projects_url}
      else
        flash[:error] =  'Project can not be created.'
        format.html { render :new  }
      end
    end
  end

  def change_status
    if params[:bug_type] == StatusConstant::FEATURE
      @status = Bug::FEATURE_STATUS
    else
      @status = Bug::BUG_STATUS
    end
    render :partial => "status", :locals =>{:status=> @status}
  end

  def bug_status
    bug = Bug.find(params[:bug_id])
    bug.update_columns(status: params[:status]) if bug
    if request.xhr?
        render :json => {
                            :msg => "updated"
                        }
     end
  end

  private

  def bug_params
    params.require(:bug).permit(:title, :description, :status, :bug_type, :deadline, :screen_shot, :creator_id, :user_id, :project_id)
  end

  def get_users
    @users = User.all
  end

  def set_project
    @project = Project.find(params[:project_id])
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_action :authenticate_user!
  before_action :set_project, only: [:edit, :destroy, :update]
  before_action :get_users, only: [:new, :edit, :create]

  def index
    if current_user.has_role RoleConstant::MANAGER
      @projects = Project.newest_first
    else
      @projects = current_user.projects.newest_first
    end
  end

  def new
    @project = Project.new
  end

  def edit
  end

  def create
    @project = Project.new(project_params)
    respond_to do |format|
			if @project.save
				flash[:success]= "Project was successfully created."
				format.html { redirect_to projects_url}
			else
				flash[:error] =  'Project can not be created.'
				format.html { render :new  }
			end
		end
  end

  def update
    respond_to do |format|
			if @project.update(project_params)
				flash[:success]= "Project was successfully updated."
				format.html { redirect_to projects_url}
			else
				flash[:error] = 'Project can not be updated.'
				format.html { render :edit  }
			end
		end
  end

  def destroy
    @project.destroy
    respond_to do |format|
    	flash[:notice]= 'Project was successfully destroyed.'
      format.html { redirect_to projects_url }
    end
	end


  private

	def project_params
		params.require(:project).permit(:title, :description, :user_ids => [])
	end

  def set_project
    @project = Project.find(params[:id])
  end

  def get_users
    @users = User.all
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:user_type, :name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:user_type, :name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :authenticate_user!

  def index
    @users = User.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bugs_helper.rb
module BugsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bugs/_form.html.erb
<%= form_for([@project, @bug]) do |f| %>
   <div class="form-group">
      <%=f.label :title%>
       <%=f.text_field :title ,class: 'form-control', placeholder: 'Enter title'%>
   </div>
   <div class="form-group">
      <%=f.label :description%>
       <%=f.text_area :description ,class: 'form-control', placeholder: 'Description'%>
   </div>
   <div class="form-group">
      <%=f.label :deadline%>
       <%=f.date_field :deadline ,class: 'form-control', placeholder: 'Description'%>
   </div>
   <div class="form-group">
      <%=f.label :user%>
      <%=f.select :user_id, @users.map{ |c| [c.name, c.id] }, {prompt: "Select User"}, {class: 'form-control'}%>
   </div>
   <div class="form-group">
     <%= f.label :bug_type %><br />
     <%= f.select :bug_type, Bug.bug_types.keys, {}, :onchange => "update_status_div(this.value )" %>
  </div>
  <div class="form-group">
    <%= f.label :screen_shot %><br />
    <%= f.file_field :screen_shot %>
 </div>
 <%= f.hidden_field :creator_id, :value => current_user.id %>
 <%= f.hidden_field :project_id, :value => @project.id %>
 <div class="form-group" id="status">
    <%= render :partial => 'status', :locals=>{:f=>f, :status=>Bug::FEATURE_STATUS}  %>
 </div>
   <div><p><%= f.submit 'Submit', class: "btn btn-default" %>
<% end %>

app/views/bugs/_status.html.erb
<%= select_tag "bug[status]", options_for_select(status) %>

app/views/bugs/index.html.erb
<div class="container">
  <h2>Projects</h2>
  <%= link_to('New Project', new_project_path, class: 'btn btn-success')  %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Title</th>
        <th>Feature</th>
        <th>Bug</th>
        <th>User</th>
        <th>Screen Shot</th>
        <th>Deadline</th>
        <th>Status</th>
      </tr>
    </thead>
    <tbody>
      <% @bugs.each do |bug|%>
      <tr>
        <td><%= bug.title %></td>
        <td><%= bug.check_feature ? "Yes" : "No"%></td>
        <td><%= bug.check_bug ? "Yes" : "No"%></td>
        <td><%= bug.user.name%></td>
        <td>
          <%if bug.screen_shot.exists?%>
          <img src="<%= bug.screen_shot.url(:thumb)%>" alt="">
          <%else %>
          No Image
          <%end%>
        </td>
        <td><%= bug.deadline.strftime('%d %b %Y') if bug.deadline%></td>
        <td>
          <% if bug.check_feature%>
            <%= select_tag 'Status', options_for_select(Bug::FEATURE_STATUS, :selected=>bug.status), {:onchange=>"bug_status(this.value, #{bug.id});"}%>
          <% else %>
            <%= select_tag 'Status', options_for_select(Bug::BUG_STATUS, :selected=>bug.status), {:onchange=>"bug_status(this.value, #{bug.id});"}%>
          <% end %>

        </td>

      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/bugs/new.html.erb
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
              <h2>Project Name: <%= @project.title %></h2>
                Add Bug Form
            </div>
            <%= render "shared/error_messages", :target => @bug %>
            <div class="panel-body">
                <div class="row">
                    <div class="col-lg-12">
                        <%= render 'form' %>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/bugs/show.html.erb
<div class="container">
  <h2>Projects</h2>
  <%= link_to('New Project', new_project_path, class: 'btn btn-success')  %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Title</th>
        <th>User</th>
        <th>Feature</th>
        <th>Bug</th>
        <th>Screen Shot</th>
        <th>Status</th>
      </tr>
    </thead>
    <tbody>
      <% @bugs.each do |bug|%>
      <tr>
        <td><%= bug.title %></td>
        <td><%= bug.user.name%></td>
        <td><%= bug.check_feature%></td>
        <td><%= bug.check_bug%></td>
        <td>
          <%if bug.screen_shot.exists?%>
          <img src="<%= bug.screen_shot.url(:thumb)%>" alt="">
          <%else %>
          No Image
          <%end%>
        </td>
        <td><%= bug.status%></td>

      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Demo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render :partial => "/shared/header" %>
    <%= yield %>
    <% unless flash.empty? %>
          <script type="text/javascript">
              <% flash.each do |f| %>
              <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
             toastr['<%= type %>']('<%= f[1] %>');
            <% end %>
          </script>
      <% end %>
    <%= render :partial => "/shared/footer" %>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
   <div class="form-group">
      <%=f.label :title%>
       <%=f.text_field :title ,class: 'form-control', placeholder: 'Enter title'%>
   </div>
   <div class="form-group">
      <%=f.label :description%>
       <%=f.text_area :description ,class: 'form-control', placeholder: 'Description'%>
   </div>
   <div class="form-group">
      <%=f.label :user%>
      <%=f.select :user_ids, @users.map{ |c| [c.name, c.id] }, {prompt: "Select Users"}, {:multiple => true, class: 'form-control'}%>
   </div>
   <div><p><%= f.submit 'Submit', class: "btn btn-default" %>
<% end %>

app/views/projects/edit.html.erb
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Edit Project Form
            </div>
            <%= render "shared/error_messages", :target => @project %>
            <div class="panel-body">
                <div class="row">
                    <div class="col-lg-12">
                        <%= render 'form' %>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/projects/index.html.erb
<div class="container">
  <h2>Projects</h2>
  <%= link_to('New Project', new_project_path, class: 'btn btn-success')  %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Title</th>
        <th>Bugs</th>
        <th>Feature</th>
        <th>Action</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @projects.each do |project|%>
      <tr>
        <td><%= project.title %></td>
        <td><%= project.bugs.bug.count%></td>
        <td><%= project.bugs.feature.count%></td>
        <td class="center">
            <span>
              <%= link_to 'edit', edit_project_path(project) %>
            </span>
            <span>
                <%= link_to 'delete',  project_path(project),  method: :delete, data: { confirm: 'Are you sure?' } %>
            </span>
        </td>
        <% unless current_user.has_role RoleConstant::DEVELOPER%>
          <td><%= link_to 'Add Bug', new_project_bug_path(project), class: "btn btn-info" %></td>
        <% end %>
        <td><%= link_to 'Show Bugs', project_bug_path(project, project.id), class: "btn btn-success" %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/projects/new.html.erb
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Project Form
            </div>
            <%= render "shared/error_messages", :target => @project %>
            <div class="panel-body">
                <div class="row">
                    <div class="col-lg-12">
                        <%= render 'form' %>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/shared/_error_messages.html.erb
<% if target and target.errors.any? %>
	<div class="error_explanation">
		<h2><%= pluralize(target.errors.count, "error") %> prevented this record from being saved:</h2>
		<ul>
			<% target.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">

  <div class="container text-center">
    <div class="content">Copyright 2016 | All Rights Reserved | Powered by <a href="/">My Rails App</a></div>
  </div>

</footer>

app/views/shared/_header.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Rails App</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="<%= users_path%>">Users</a></li>
      <li><a href="<%= projects_path%>">Projects</a></li>
        <li><a href="<%= bugs_path%>">My Bugs</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li>
        <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
        </li>
      <% else %>
        <li>
        <%= link_to('Login', new_user_session_path)  %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/users/index.html.erb
<div class="container">
  <h2>Users</h2>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>email</th>
        <th>Role</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user|%>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email%></td>
        <td><%= user.user_type%></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>